spring:
  application:
    name: datn
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/datn}
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: daohuucong123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: phonezone.shop11@gmail.com
    password: koyi qojj mijo zohp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 8080
  servlet:
    context-path: /datn
cloudinary:
  cloud-name: da4p9sh2j
  api-key: 188561129188545
  api-secret: P2sJ6y2Xq2_aqvmZqhaze_wwLuc
  secure: true
jwt:
  signerKey: "bf9204f8dcf907346f3fb5e76523ecd1e28a1941dd2424699378bf9b36e127284cd6e1b238e356c99598beec19c0debce0f89f0710f15246c62edca1a49a78ae6a862f30369eb952c11f42fc8814835264823663984a6a9a0960a7a7150ee2df0901eef78d4eb0de122ecd2ec4c0e8885a13c8dcea0d24bbcbe86deee3ad554a4bfd5473b500ec07e74c62911eea9041b9b28e72544f19263db986a2a9938fa3e3c43c3a2d3ecaefe5b3eba642e6a56e5ed7bfb710c7f596da6e37004bd374a6d6b3ed82be43fdf0eb8cd2e76fa972e7d092a0f3630e92532e9abd9ae92d6445cc0bae6516aae4b0380b148dbb182436a70f2893551b0ae50bc6f9be00ea7dab"
  valid-duration: 6000 # in second
  refreshtable-duration: 1200 # in seconds

vnpay:
  tmn-code: XTKS4ZS4
  hash-secret: 38BJLQOEGNK84OS6GNQ66NIP2LI6HAMG
  url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  refund-url: https://sandbox.vnpayment.vn/merchant_webapi/api/transaction
  return-url: http://localhost:8080/datn/payment/vnpay-return
momo:
  url: https://test-payment.momo.vn/v2/gateway/api/create
  refund-url: https://test-payment.momo.vn/v2/gateway/api/refund
  access-key: mTCKt9W3eU1m39TW
  partner-code: MOMOLRJZ20181206
  secret-key: SetA5RDnLHvt51AULf51DyauxUo3kDU6
  return-url: https://088e-2402-800-63b6-9b27-b497-4453-825e-43fb.ngrok-free.app/datn/payment/momo-return
  notify-url: https://088e-2402-800-63b6-9b27-b497-4453-825e-43fb.ngrok-free.app/datn/payment/momo-notify

